### PR TITLE
Switched SurfacePolyline from Location to Position in GeoJSONParser

### PR DESCRIPTION
**Pull request by ghost**
### Description of the Change

Working on GeoJSONParser to use both SurfacePolylines and Paths.

### Why Should This Be In Core?

To parse GeoJSON LineStrings that are 3D (not clamped to surface).

### Benefits

3D lines can be drawn above the globe.

### Potential Drawbacks

None.

### Applicable Issues

The code is currently commented out because when "../../shapes/Path" is included, Chrome gives the error "Placemark.constructor: The specified position is null or undefined.".  Oddly this error happens before parsing a test GeoJSON file.  It's not clear what exactly is happening.  More eyes on this would be helpful.

### CODE REVIEW

**Comment by EMaksymenko** [comment]
Could you give test case how to debug that issue with Placemark constructor?

**Comment by ghost** [comment]
I just have a simple application that loads and displays a GeoJSON file.

**Comment by ghost** [comment]
I finally had some time to look at this problem.  It was a simple fix... I had forgotten to put "Path" in the top level function() call.

**Comment by EMaksymenko** [comment]
Ok. I will review and merge later today.

**Comment by EMaksymenko** [comment]
@lowswaplab i just noticed after merge, why we cut this part of code? Should we put it back?
```
                if (configuration.highlightAttributes) {
                    shape.highlightAttributes = configuration.highlightAttributes;
                }
                if (configuration && configuration.pickDelegate) {
                    shape.pickDelegate = configuration.pickDelegate;
                }
                if (configuration && configuration.userProperties) {
                    shape.userProperties = configuration.userProperties;
                }
```
Знімок екрану з 2021-05-26 19-39-14

**Comment by ghost** [comment]
I don't know how that code disappeared... I think it was a mistake and should be put back in.

**Comment by EMaksymenko** [comment]
Ok. I have committed code back. It was removed in 5610a5a commit

**Pull request merged**
