### PR TITLE
KML IconStyle sets icon color

### PR DESCRIPTION
**Pull request by ghost**
### Description of the Change

Set icon color according to KML IconStyle color tag

### Why Should This Be In Core?

To better support KML files.

### Benefits

To better support KML files.

### Potential Drawbacks

None.

### Applicable Issues

None.

### CODE REVIEW

**Comment by EMaksymenko** [comment]
Please, remove duplicate in condition:
style.kmlColorMode && style.kmlColorMode

**Comment by ghost** [comment]
Done.

The next PR I want to do is use the KML "heading" tag to rotate the icon.  The problem is that Placemark have "imageRotation" and "imageRotationReference" variables.  Those should probably be in PlacemarkAttributes.  (There are actually a lot of attributes that should probably be in PlacemarkAttributes instead of the Placemark itself.)

The code I've tested has imageRotation and imageRotationReference duplicated in PlacemarkAttributes.  I don't think this is a good idea duplicating variables...

**Comment by EMaksymenko** [comment]
I think you can update Placemark attributes from KML style in that place, where you put a code in previous closed PR.

**Comment by ghost** [comment]
I think I found where Placemark variables (e.g. altitudeMode) are used in KmlPlacemark.js: this._renderable.altitudeMode.

I'll try to do something similar with imageRotation and imageRotationReference.

**Pull request merged**
