### PR TITLE
Added configuration parameters to GeoJSONParser

### PR DESCRIPTION
**Pull request by ghost**
### Description of the Change
Added configuration parameters to GeoJSONParser: altitudeMode, eyeDistanceScaling, eyeDistanceScalingThreshold, imageRotation, and imageRotationReference

### Why Should This Be In Core?
So GeoJSONParser shareComfigurationCallback() functions can set those various parameters for the resulting placemarks.

### Benefits
Greater control over how placemarks are rendered on the map.

### Potential Drawbacks
None.

### Applicable Issues
None.

### CODE REVIEW

**Comment by EMaksymenko** [comment]
Hi,

To merge your request, please answer two questions:
1) Should we add "configuration &&" check for highlightAttributes code simmilar as to all other attributes in this commit https://github.com/WorldWindEarth/worldwindjs/pull/51/commits/9191c8ccf21c219ba9a7bd7a6576b8354f36ccf3?
```
if (configuration.highlightAttributes) {
    placemark.highlightAttributes = configuration.highlightAttributes;
}
```
2) Please, explain in few words, why did you change SurfacePolycon to vector Polygon?

**Comment by ghost** [comment]
1) Yes.
2) Switching from SurfacePolygon to Polygon was going to be a separate pull request, but it ended up in this one accidentally... I want to draw 3D lines, polygons, etc via GeoJSON and I worked on polygons first.

**Comment by EMaksymenko** [comment]
1. Could you commit this "configuration &&" fix, please?
2. If you want to implement all vector graphics, let's may be roll back last commit and track whole feature in separete PR?

And I think we need to make support of both Surface and Vector lines. If figure has no points with altitude it must be surface shape to correctly follow terrain and be more performance effective. What do you think?

**Comment by EMaksymenko** [comment]
@PJHogan you have merged PR with error and I cannot revert it.

Could you please revert it. We need few fixes described above.

**Comment by EMaksymenko** [comment]
@PJHogan  and @lowswaplab,

I have:
- closed reversed PR #52.
- reverted last merge PR #51 manually.
- added "configuration &&" fix and rolled back SurfacePolygon commit
- commited everything back manually into develop branch.

@lowswaplab, please, pull develop branch with rebase and create new PR for Polygon and other vector graphics support.

**Pull request merged**
